---
# Installs and configures uWSGI python app in a docker container

# TODO: May not need this anymore with new workflow
# Create the user (if necessary)
- user: name={{ appuser }} shell=/bin/bash createhome=yes group=www-data groups=docker
  when: appuser == "www-data"

- name: make sure .ssh folder exists for app
  file: path=/var/www/.ssh mode=700 state=directory owner=www-data

- name: add the authorized keys
  authorized_key: user=www-data key="{{ item }}"
  with_items: authorized_keys
# END TODO

- name: run app container
  docker:
    name: "{{ app_name }}"
    command: uwsgi {{ uwsgi_ini }}
    registry: "{{ registry }}"
    image: "{{ image }}"
    # TODO: reloaded doesn't work with ansible 1.9.1
    state: restarted
    docker_api_version: "{{ docker_api_version }}"
    # TODO: or 'always'?
    restart_policy: on-failure
    env: "{{ env_vars }}"

# TODO: Add a docker cleanup command?
