---
# Installs and configures uWSGI python app in a docker container

- name: run app container
  docker:
    name: "{{ app_name }}"
    command: uwsgi {{ uwsgi_ini }}
    registry: "{{ registry }}"
    image: "{{ image }}"
    # TODO: reloaded doesn't work with ansible 1.9.1
    state: restarted
    docker_api_version: "{{ docker_api_version }}"
    # TODO: or 'always'?
    restart_policy: on-failure
    env: "{{ env_vars }}"

# TODO: Add a docker cleanup command?
