- name: Make sure that apt requirements are present update_cache=yes cache_valid_time=3600
  apt: name={{ item }} state=present
  with_items:
    - python-apt
    - python-pycurl

- name: Add the debian wheezy-backports repo
  apt_repository: repo='deb http://ftp.us.debian.org/debian wheezy-backports main' state=present
  when: ansible_distribution == "Debian"  # Should make sure this is wheezy at some point, but for now, fuck it.

- name: Install nodejs
  apt: name=nodejs state=present default_release=wheezy-backports

# So, it turns out that debian is fucking stupid, and installs node at /usr/bin/nodejs, WHICH IS NOT THE RIGHT BINARY NAME
- name: Symlink the node BINARY
  file: state=link src=/usr/bin/nodejs path=/usr/bin/node

- name: Check if npm is installed
  command: which npm
  register: npm_installed
  ignore_errors: True

- name: Get the npm install script
  get_url: dest=/tmp/npm_install.sh url=https://www.npmjs.org/install.sh
  when: npm_installed|failed

- name: Install npm
  raw: sh /tmp/npm_install.sh
  when: npm_installed|failed