---
# This task installs and configures uwsgi from source

# source | Install build requirements
- apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  when: not uwsgi_python_3
  with_items:
    - build-essential
    - python
    - python-dev

# source | Install build requirements
- apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  when: uwsgi_python_3
  with_items:
    - build-essential
    - python3
    - python3-dev

- name: source | Check if uwsgi is installed
  command: which uwsgi
  register: uwsgi_exists
  ignore_errors: true

- name: source | Download the source package
  get_url: url=http://projects.unbit.it/downloads/uwsgi-{{ uwsgi_version }}.tar.gz dest=/tmp/uwsgi.tar.gz
  when: uwsgi_exists|failed and uwsgi_version != None

- name: source | Download the source package
  get_url: url=http://projects.unbit.it/downloads/uwsgi-latest.tar.gz dest=/tmp/uwsgi.tar.gz
  when: uwsgi_exists|failed and uwsgi_version == None

- name: source | Create the extraction directory
  file: path=/tmp/uwsgi state=directory

- name: source | Unpack the source
  command: tar xzf /tmp/uwsgi.tar.gz -C /tmp/uwsgi/ --strip-components=1
  when: uwsgi_exists|failed

- name: source | Build uwsgi
  command: make PROFILE=nolang chdir=/tmp/uwsgi
  when: uwsgi_exists|failed

- name: source | Build python2 plugin
  shell: PYTHON=python2 ./uwsgi --build-plugin "plugins/python python2" chdir=/tmp/uwsgi executable=/bin/bash
  when: uwsgi_exists|failed

- name: source | Build python32 plugin
  shell: PYTHON=python3 ./uwsgi --build-plugin "plugins/python python3" chdir=/tmp/uwsgi executable=/bin/bash
  when: uwsgi_exists|failed

- name: source | Move the binary
  command: mv /tmp/uwsgi/uwsgi /usr/bin/uwsgi
  when: uwsgi_exists|failed

- name: source | Create the plugins directory
  file: path=/etc/uwsgi-emperor/plugins/ state=directory
  when: uwsgi_exists|failed

- name: source | Move the plugins
  command: mv /tmp/uwsgi/{{ item }} /etc/uwsgi-emperor/plugins/ 
  with_items:
    - python2_plugin.so
    - python3_plugin.so
  when: uwsgi_exists|failed

- name: Set the binary path
  set_fact: uwsgi_binary="/usr/bin/uwsgi"

- include: setup-initd.yml