---
# This task installs uwsgi using pip, which is a good way to get a very recent version with python support.

- name: pip | Make sure that pip is installed
  apt: name={{ item }} update_cache=yes cache_valid_time=3600
  when: not uwsgi_python_3
  with_items:
    - python-dev
    - python-pip

- name: pip | Make sure that pip is installed
  apt: name={{ item }} update_cache=yes cache_valid_time=3600
  when: uwsgi_python_3
  with_items:
    - build-essential
    - python3-dev
    - python3
    - python3-pip

- name: pip | Make sure that uwsgi is installed
  pip: name=uwsgi state=latest executable={% if uwsgi_python_3 %}pip-3.2{% else %}pip{% endif %}
  when: uwsgi_version == None

- name: pip | Make sure that uwsgi is installed
  pip: name=uwsgi version={{ uwsgi_version }} executable={% if uwsgi_python_3 %}pip-3.2{% else %}pip{% endif %}
  when: uwsgi_version != None

- name: Set the binary path
  set_fact: uwsgi_binary="/usr/local/bin/uwsgi"

- include: setup-initd.yml