---
- name: Verify running Debian 8+
  fail: msg="Docker requires Debian 8 Jessie"
  when: ansible_distribution == "Debian" and ansible_distribution_major_version < "8"

# Install Docker via backports
- apt_repository: repo="deb http://http.debian.net/debian jessie-backports main" update_cache=yes
  when: docker_install_method == "apt"
- name: install docker (apt)
  apt: name=docker.io state=present update_cache=yes
  when: docker_install_method == "apt"

# Install docker via web script
- name: install docker (script)
  shell: curl -sSL https://get.docker.com/ | sh
  args:
    creates: /usr/bin/docker
  when: docker_install_method == "script"

- name: add ansible to docker group
  user: name=ansible groups=docker append=yes

- name: make sure docker is started (and runs on boot)
  service: name=docker state=started enabled=yes

# Install latest PIP (base version is too old for docker-py)
- shell: curl -sSL --retry 5 https://bootstrap.pypa.io/get-pip.py | sudo python2.7
  args:
    creates: /usr/local/bin/pip

- name: install python docker client (allows ansible control)
  pip: name=docker-py executable=/usr/local/bin/pip

- name: install common scripts
  copy: src=scripts/{{ item }} dest=/usr/local/bin/{{ item }} mode=755
  with_items:
    - docker_cleanup
    - detect_exposed_port

- cron: name="docker cleanup" special_time="weekly" user=ansible job="/usr/local/bin/docker_cleanup"
