---
# This task installs and configures uwsgi from source
- name: source | Install build requirements
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - build-essential
    - python
    - python-dev

- name: source | Check if uwsgi is installed
  command: which uwsgi
  register: uwsgi_exists
  ignore_errors: true

- name: source | Download the source package
  get_url: url=http://projects.unbit.it/downloads/uwsgi-{{ uwsgi_version }}.tar.gz dest=/tmp/uwsgi-{{ uwsgi_version }}.tar.gz
  when: uwsgi_exists|failed

- name: source | Unpack the source
  command: tar xzf uwsgi-{{ uwsgi_version }}.tar.gz -C chdir=/tmp/
  when: uwsgi_exists|failed

- name: source | Build uwsgi
  command: make chdir=/tmp/uwsgi-{{ uwsgi_version }}
  when: uwsgi_exists|failed

- name: source | Move the binary
  command: mv /tmp/uwsgi-{{ uwsgi_version }}/uwsgi /usr/bin/uwsgi
  when: uwsgi_exists|failed

# Set the binary path
- set_fact: uwsgi_binary="/usr/bin/uwsgi"

- include: setup-initd.yml