---
- name: install pound
  apt: name=pound state=present update_cache=true
  notify: start pound
  tags:
    - install

- name: create run directory
  file: dest={{ pound_run_path }}
    state=directory
    owner={{ pound_user }}
    group={{ pound_group }}
  tags:
    - install
    - config

- name: copy ssl certs
  copy: src={{ item }}
    dest="{{ pound_conf_path }}{{ item.split('/')[-1] }}"
    owner={{ pound_user }}
    group={{ pound_group }}
    mode=0400
  with_items: pound_ssl_certs
  when: pound_ssl_certs
  ignore_errors: True
  tags:
    - install
    - config

- name: set pound environment startup sentinel
  lineinfile: dest=/etc/default/pound regexp="startup=0" line="startup=1"
  tags:
    - config

- name: create pound configuration
  template: src=pound.cfg.j2
    dest={{ pound_conf_path }}pound.cfg
  notify: restart pound
  tags:
    - install
    - config
