---

# Test for directories that should exist
- shell: test -d {{ item }}
  with_items:
    - "{{ ps_config_path }}"

# Test for files that should exist
- shell: test -e {{ item }}
  with_items:
    -  "{{ ps_config_path }}/postgresql.conf"
    -  "{{ ps_config_path }}/pg_hba.conf"
    -  "{{ ps_config_path }}/pg_ctl.conf"
    -  "{{ ps_config_path }}/pg_ident.conf"
    -  "{{ ps_config_path }}/start.conf"
    -  "{{ ps_config_path }}/environment"

