---
# downloads and sets up grafana

- name: influxdb | create folder
  shell: mkdir -p ~/grafana

- name: grafana | copy tarball
  copy: src=grafana-1.9.0.tar.gz dest=~/grafana

- name: grafana | extract archive
  shell: tar -xzf ~/grafana/grafana-1.9.0.tar.gz -C ~/

- name: grafana | create directories
  shell: mkdir -p /var/www/grafana

- name: grafana | chown
  shell: chown -R www-data:www-data /var/www/grafana

- name: grafana | copy source
  shell: cp -r ~/grafana-1.9.0/* /var/www/grafana/

- name: grafana | copy config
  template: src=grafana_config.js dest=/var/www/grafana/config.js
