---

- name: Make sure elasticsearch is started
  shell: test -e /var/run/elasticsearch.pid

- name: Wait for elasticsearch to respond
  wait_for: port=9200 timeout=30

- name: Check to make sure that we can get the status
  shell: curl http://192.168.22.234:9200/_status