---
# Installs and configures uWSGI python app in a docker container

# Create the user (if necessary)
- user: name={{ appuser }} shell=/bin/bash createhome=yes group=www-data groups=docker
  when: appuser == "www-data"
  tags: docker

## Create the app user (if necessary)
#- user: name={{ app_name }} shell=/bin/bash createhome=yes group=www-data
#  tags: docker

- name: make sure .ssh folder exists for app
  file: path=/var/www/.ssh mode=700 state=directory owner=www-data
  tags: docker

- name: add the authorized keys
  authorized_key: user=www-data key="{{ item }}"
  with_items: authorized_keys
  tags: docker

## Create a uwsgi configuration file
#- template: src=uwsgi.ini.j2 dest=/etc/uwsgi-emperor/vassals/{{ app_name }}.ini owner={{ appuser }} group=www-data
#  when: app_enabled
#  tags: docker
