---
- name: Add apt key for icinga repo
  apt_key: url=http://packages.icinga.org/icinga.key id=34410682 state=present

- name: Install icinga PPA (Debian 7)
  apt_repository: repo="deb http://packages.icinga.org/debian icinga-wheezy main"
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "7"

- name: Install icinga PPA (Debian 8)
  apt_repository: repo="deb http://packages.icinga.org/debian icinga-jessie main"
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "8"

- name: Install icinga2
  apt: name={{ item }} update_cache=yes state={{ icinga_apt_state | default("present") }}
  with_items:
    - icinga2
    - nagios-plugins

- name: Copy check plugins
  copy: src=plugins/ dest=/usr/lib/nagios/plugins/ mode=755 owner=root group=root

- name: Copy remote command config
  copy: src=commands.conf dest=/etc/icinga2/conf.d/commands.conf owner=root group=root mode=644
  when: ansible_hostname != "monitor01"
  notify: Reload icinga2

#- name: Enable Icinga2 features
#  command: /usr/sbin/icinga2 feature enable {{ item }}
#  args:
#    creates: /etc/icinga2/features-enabled/{{ item }}.conf
#  with_items:
#    - api
#  notify: Restart icinga2

- service: name=icinga2 state=started
