---

- name: pip | Make sure that pip is installed
  apt: name={{ item }} update_cache=yes cache_valid_time=3600
  with_items:
    - python-dev
    - python-pip

# Make sure that virtualenv is installed
- pip: name=virtualenv state=present

# Create the app user (if necessary)
- user: name={{ graphite_user }} shell=/bin/bash createhome=yes

- name: Set the graphite_virtualenv
  set_fact: graphite_virtualenv="/var/venvs/graphite"
  when: not graphite_virtualenv

- name: Make sure that the virtual env directory exists
  file: path={{ graphite_virtualenv }} state=directory owner={{ graphite_user }}

- name: Install carbon
  pip: name={{ carbon_install }} virtualenv={{ graphite_virtualenv }}

- name: Install whisper
  pip: name={{ whisper_install }} virtualenv={{ graphite_virtualenv }}

- name: Install ceres
  pip: name={{ ceres_install }} virtualenv={{ graphite_virtualenv }}