---

# Install PyCurl, and Java
- apt: name=python-pycurl state=present update_cache=yes cache_valid_time=3600

- name: Add the logstash apt key
  apt_key: url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch state=present

- name: Add the logstash apt repo
  apt_repository: repo=" deb http://packages.elasticsearch.org/logstash/1.3/debian stable main" state=present

- name: Make sure logstash is installed
  apt: name=logstash state=latest
  when: logstash_version == None

# - name: Add logstash input configs
#   template: src=input.conf.j2 dest=/etc/logstash/conf.d/{{ item.keys()[0] }}.conf
#   with_items: logstash_inputs

- name: Enable logstash
  lineinfile: dest=/etc/default/logstash line="START=yes" regexp="^START="
  when: logstash_enabled == True

- name: Make sure logstash is started
  service: name=logstash state=started
  when: logstash_enabled == True

- name: Disable logstash
  lineinfile: dest=/etc/default/logstash line="START=no" regexp="^START="
  when: logstash_enabled == False

- name: Make sure logstash is stopped
  service: name=logstash state=stopped
  when: logstash_enabled == False

