---

- name: Install the memcached packages 
  apt: name=memcached state=present update_cache=yes

- name: Set the max open file descriptors 
  sysctl: name=fs.file-max value={{ memcached_fs_file_max }} state=present

- name: Copy the client configuration file 
  template: src=memcached.conf.j2 dest=/etc/memcached.conf
  notify: restart memcached

- name: start the memcached service
  service: name=memcached state=started enabled=yes